version: '3.3'
services:
    worker:
        build: .
        container_name: worktime_node
        ports:
            - 8080:8080
        volumes:
            - .:/usr/worktime
            - '/usr/worktime/node_modules'
        depends_on:
            - mongo
        environment:
            - DB_HOST=mongo
            - DB_PORT=27017
            - DB_USER=${DB_USER}
            - DB_PASS=${DB_PASS}
            - DB_NAME=${DB_NAME}
            - DEBUG='grammy*'
    mongo:
        image: mongo
        restart: always
        volumes:
            - 'mongovolume0i1:/var/lib/mongodb/database'
            - './docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d'
        environment:
            - MONGO_INITDB_ROOT_USERNAME=${DB_ADMIN_USER}
            - MONGO_INITDB_ROOT_PASSWORD=${DB_ADMIN_PASS}
            - MONGO_INITDB_DATABASE=${DB_NAME}
            - MONGO_USER=${DB_USER}
            - MONGO_PASS=${DB_PASS}
volumes:
    mongovolume01:
        driver: local
